TARGET_SKILLS = {
    "python": 10,
    "retrieval": 10,
    "ranking": 10,
    "embeddings": 10,
    "vector database": 9,
    "rag": 8,
    "nlp": 8,
    "llm": 8,
    "fine-tuning": 7,
    "pinecone": 7,
    "weaviate": 7,
    "qdrant": 7,
    "milvus": 7,
    "faiss": 7,
    "elasticsearch": 7,
    "opensearch": 7,
    "recommendation systems": 9,
    "search": 9,
}
FOUNDER_KEYWORDS = [
    "built",
    "launched",
    "owned",
    "shipped",
    "designed",
    "architected",
    "deployed",
    "created",
    "scaling",
    "production",
]
NEGATIVE_KEYWORDS = [
    "academic",
    "research lab",
    "research only",
    "theoretical",
    "marketing manager",
]
RELEVANT_TITLES = [
    "ai engineer",
    "machine learning engineer",
    "ml engineer",
    "search engineer",
    "recommendation systems engineer",
    "recommendation engineer",
    "applied scientist",
    "data scientist",
    "nlp engineer",
    "information retrieval engineer",
    "relevance engineer",
    "ranking engineer",
    "ai researcher",
]
BAD_TITLES = [
    "hr manager",
    "marketing manager",
    "content writer",
    "civil engineer",
    "mechanical engineer",
    "customer support",
    "project manager",
]